todolist-web-struts/src/main/java/io/github/benas/todolist/web/action/user/AccountAction.java
/*
 * The MIT License
 *
 *   Copyright (c) 2013, benas (md.benhassine@gmail.com)
 *
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *   of this software and associated documentation files (the "Software"), to deal
 *   in the Software without restriction, including without limitation the rights
 *   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *   copies of the Software, and to permit persons to whom the Software is
 *   furnished to do so, subject to the following conditions:
 *
 *   The above copyright notice and this permission notice shall be included in
 *   all copies or substantial portions of the Software.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *   THE SOFTWARE.
 */

package io.github.benas.todolist.web.action.user;

import com.opensymphony.xwork2.Action;
import com.opensymphony.xwork2.ActionSupport;
import io.github.todolist.core.domain.User;
import io.github.benas.todolist.web.common.form.ChangePasswordForm;
import io.github.benas.todolist.web.common.form.RegistrationForm;
import io.github.benas.todolist.web.common.util.TodolistUtils;
import io.github.benas.todolist.web.action.BaseAction;

import javax.validation.ConstraintViolation;
import java.text.MessageFormat;
import java.util.Set;

/**
 * Action class for Account CRUD operations.
 *
 * @author benas (md.benhassine@gmail.com)
 */
public class AccountAction extends BaseAction {

    private ChangePasswordForm changePasswordForm;

    private RegistrationForm registrationForm;

    private User user;

    private String updateProfileSuccessMessage, updatePasswordSuccessMessage;

    private String error, errorFirstName, errorLastName, errorEmail, errorPassword,
            errorCurrentPassword, errorConfirmationPassword, errorConfirmPasswordMatching;

    public String account() {
        user = getSessionUser();
        return Action.SUCCESS;
    }

    public String register() {
        return Action.SUCCESS;
    }

    public String doRegister() {

        /*
         * Validate registration form using Bean Validation API
         */
        Set<ConstraintViolation<RegistrationForm>> constraintViolations = validator.validateProperty(registrationForm, "firstname");
        if (constraintViolations.size() > 0) {
            errorFirstName = constraintViolations.iterator().next().getMessage();
            error =  getText("register.error.global");
        }

        constraintViolations = validator.validateProperty(registrationForm, "lastname");
        if (constraintViolations.size() > 0) {
            errorLastName = constraintViolations.iterator().next().getMessage();
            error = getText("register.error.global");
        }

        constraintViolations = validator.validateProperty(registrationForm, "email");
        if (constraintViolations.size() > 0) {
            errorEmail = constraintViolations.iterator().next().getMessage();
            error = getText("register.error.global");
        }

        constraintViolations = validator.validateProperty(registrationForm, "password");
        if (constraintViolations.size() > 0) {
            errorPassword = constraintViolations.iterator().next().getMessage();
            error = getText("register.error.global");
        }

        constraintViolations = validator.validateProperty(registrationForm, "confirmationPassword");
        if (constraintViolations.size() > 0) {
            errorConfirmationPassword = constraintViolations.iterator().next().getMessage();
            error = getText("register.error.global");
        }

        if (!registrationForm.getConfirmationPassword().equals(registrationForm.getPassword())) {
            errorConfirmPasswordMatching = getText("register.error.password.confirmation.error");
            error = getText("register.error.global");
        }

        if (error != null) {
            return ActionSupport.INPUT;//if invalid input, do not continue to business constraints validation
        }

        if (userService.getUserByEmail(registrationForm.getEmail()) != null ) {
            error = MessageFormat.format(getText("register.error.global.account"), registrationForm.getEmail());
            return ActionSupport.INPUT;
        }

        /*
         * Validation ok, register the user
         */
        User user = new User(registrationForm.getFirstname(), registrationForm.getLastname(), registrationForm.getEmail(), registrationForm.getPassword());
        user = userService.create(user);
        session.put(TodolistUtils.SESSION_USER, user);
        return Action.SUCCESS;
    }

    public String doUpdate() {
        User user = getSessionUser();
        if (userService.getUserByEmail(this.user.getEmail()) != null && !this.user.getEmail().equals(user.getEmail())) {
            error = MessageFormat.format(getText("account.email.alreadyUsed"), this.user.getEmail());
            return Action.INPUT;
        } else { // validation ok
            user.setFirstname(this.user.getFirstname());
            user.setLastname(this.user.getLastname());
            user.setEmail(this.user.getEmail());
            userService.update(user);
            session.put(TodolistUtils.SESSION_USER, user);
            updateProfileSuccessMessage = getText("account.profile.update.success");
            return Action.SUCCESS;
        }
    }

    public String doDelete() {
        User user = getSessionUser();
        //remove user
        userService.remove(user);

        //invalidate session
        session.put(TodolistUtils.SESSION_USER, null);
        if (session instanceof org.apache.struts2.dispatcher.SessionMap) {
            try {
                ((org.apache.struts2.dispatcher.SessionMap) session).invalidate();
            } catch (IllegalStateException e) {
                logger.error("Unable to invalidate session.", e);
            }
        }
        return Action.SUCCESS;
    }

    public String doChangePassword() {

        Set<ConstraintViolation<ChangePasswordForm>> constraintViolations = validator.validateProperty(changePasswordForm, "currentpassword");
        if (constraintViolations.size() > 0) {
            errorCurrentPassword = constraintViolations.iterator().next().getMessage();
            error = getText("account.password.error.global");
        }
        constraintViolations = validator.validateProperty(changePasswordForm, "password");
        if (constraintViolations.size() > 0) {
            errorPassword = constraintViolations.iterator().next().getMessage();
            error = getText("account.password.error.global");
        }

        constraintViolations = validator.validateProperty(changePasswordForm, "confirmpassword");
        if (constraintViolations.size() > 0) {
            errorConfirmationPassword = constraintViolations.iterator().next().getMessage();
            error = getText("account.password.error.global");
        }

        if (error != null) {
            return ActionSupport.INPUT;//if invalid input, do not continue to business constraints validation
        }

        User user = getSessionUser();
        if (!changePasswordForm.getCurrentpassword().equals(user.getPassword())) {
            errorCurrentPassword = getText("account.password.error");
            error = getText("account.password.error.global");
            return Action.INPUT;
        }

        if (!changePasswordForm.getPassword().equals(changePasswordForm.getConfirmpassword())) {
            errorConfirmationPassword = getText("account.password.confirmation.error");
            error = getText("account.password.error.global");
            return Action.INPUT;
        }

        user.setPassword(changePasswordForm.getPassword());
        user = userService.update(user);
        session.put(TodolistUtils.SESSION_USER, user);
        this.user = user;
        updatePasswordSuccessMessage = getText("account.password.update.success");
        return Action.SUCCESS;
    }

    /*
     * Getters for model attributes
     */
    public String getRegisterTabStyle() {
        return "active";
    }

    public ChangePasswordForm getChangePasswordForm() {
        return changePasswordForm;
    }

    public RegistrationForm getRegistrationForm() {
        return registrationForm;
    }

    public User getUser() {
        return user;
    }

    public String getError() {
        return error;
    }

    public String getErrorFirstName() {
        return errorFirstName;
    }

    public String getErrorLastName() {
        return errorLastName;
    }

    public String getErrorEmail() {
        return errorEmail;
    }

    public String getErrorPassword() {
        return errorPassword;
    }

    public String getErrorConfirmationPassword() {
        return errorConfirmationPassword;
    }

    public String getErrorConfirmPasswordMatching() {
        return errorConfirmPasswordMatching;
    }

    public String getUpdateProfileSuccessMessage() {
        return updateProfileSuccessMessage;
    }

    public String getUpdatePasswordSuccessMessage() {
        return updatePasswordSuccessMessage;
    }

    public String getErrorCurrentPassword() {
        return errorCurrentPassword;
    }

    /*
     * Setters for request parameters binding
     */

    public void setChangePasswordForm(ChangePasswordForm changePasswordForm) {
        this.changePasswordForm = changePasswordForm;
    }

    public void setRegistrationForm(RegistrationForm registrationForm) {
        this.registrationForm = registrationForm;
    }

    public void setUser(User user) {

todolist-web-struts/src/main/java/io/github/benas/todolist/web/action/user/HomeAction.java
/*
 * The MIT License
 *
 *   Copyright (c) 2013, benas (md.benhassine@gmail.com)
 *
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *   of this software and associated documentation files (the "Software"), to deal
 *   in the Software without restriction, including without limitation the rights
 *   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *   copies of the Software, and to permit persons to whom the Software is
 *   furnished to do so, subject to the following conditions:
 *
 *   The above copyright notice and this permission notice shall be included in
 *   all copies or substantial portions of the Software.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *   THE SOFTWARE.
 */

package io.github.benas.todolist.web.action.user;

import com.opensymphony.xwork2.Action;
import io.github.todolist.core.domain.Status;
import io.github.todolist.core.domain.Todo;
import io.github.todolist.core.domain.User;
import io.github.benas.todolist.web.action.BaseAction;

import java.util.List;

/**
 * Action class to load user's todo list in home page.
 *
 * benas (md.benhassine@gmail.com)
 */
public class HomeAction extends BaseAction {

    List<Todo> todoList;

    public String execute() {
        User user = getSessionUser();
        todoList = todoService.getTodoListByUser(user.getId());
        return Action.SUCCESS;
    }

    /*
     * Getters for model attributes
     */

    public List<Todo> getTodoList() {
        return todoList;
    }

    public String getHomeTabStyle() {
        return "active";
    }

    public int getTotalCount() {
        return todoService.getTodoListByUser(getSessionUser().getId()).size();
    }

    public int getDoneCount() {
        return todoService.getTodoListByStatus(getSessionUser().getId(), Status.DONE).size();
    }

    public int getTodoCount() {
        return todoService.getTodoListByStatus(getSessionUser().getId(), Status.TODO).size();
    }

}

todolist-web-struts/src/main/java/io/github/benas/todolist/web/action/user/SessionAction.java
/*
 * The MIT License
 *
 *   Copyright (c) 2013, benas (md.benhassine@gmail.com)
 *
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *   of this software and associated documentation files (the "Software"), to deal
 *   in the Software without restriction, including without limitation the rights
 *   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *   copies of the Software, and to permit persons to whom the Software is
 *   furnished to do so, subject to the following conditions:
 *
 *   The above copyright notice and this permission notice shall be included in
 *   all copies or substantial portions of the Software.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *   THE SOFTWARE.
 */

package io.github.benas.todolist.web.action.user;

import com.opensymphony.xwork2.Action;
import io.github.todolist.core.domain.User;
import io.github.benas.todolist.web.common.form.LoginForm;
import io.github.benas.todolist.web.common.util.TodolistUtils;
import io.github.benas.todolist.web.action.BaseAction;

/**
 * Action class that handles login/logout process.
 *
 * @author benas (md.benhassine@gmail.com)
 */
public class SessionAction extends BaseAction {

    private LoginForm loginForm;

    private String error;

    public String login() {
        return Action.SUCCESS;
    }

    public String doLogin() {
        if (userService.login(loginForm.getEmail(), loginForm.getPassword())) {
            User user = userService.getUserByEmail(loginForm.getEmail());
            session.put(TodolistUtils.SESSION_USER, user);
            return Action.SUCCESS;
        } else {
            error = getText("login.error.global.invalid");
            return Action.INPUT;
        }
    }

    public String doLogout() {
        if (session instanceof org.apache.struts2.dispatcher.SessionMap) {
            try {
                ((org.apache.struts2.dispatcher.SessionMap) session).invalidate();
            } catch (IllegalStateException e) {
                logger.error("Unable to invalidate session.", e);
            }
        }
        return Action.SUCCESS;
    }

    /*
     * Getters and setters for model attributes
     */

    public LoginForm getLoginForm() {
        return loginForm;
    }

    public void setLoginForm(LoginForm loginForm) {
        this.loginForm = loginForm;
    }

    public String getLoginTabStyle() {
        return "active";
    }

    public String getError() {
        return error;
    }

}

todolist-web-struts/src/main/webapp/WEB-INF/views/user/account.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="s" uri="/struts-tags" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="../common/header.jspf" %>

<div class="container">
    <div class="row">
        <div class="span3">
            <%@ include file="../common/sidebar.jspf" %>
        </div>
        <div class="span9">
            <div class="well">
                <div class="page-header">
                    <h1>My settings</h1>
                </div>

                <%@ include file="../common/error.jspf"%>

                <div class="row">
                    <div class="span8">
                        <s:form cssClass="form-horizontal" namespace="/user" method="post" action="update.do">
                            <fieldset>
                                <legend>Update my profile <p class="alert-success">${requestScope.updateProfileSuccessMessage}</p></legend>

                                <div class="control-group">
                                    <label class="control-label" for="firstname">First Name :</label>

                                    <div class="controls">
                                        <s:textfield name="user.firstname" id="firstname" cssClass="input-medium" required="required"/>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="lastname">Last Name :</label>

                                    <div class="controls">
                                        <s:textfield name="user.lastname" id="lastname" cssClass="input-medium" required="required"/>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="email">Email :</label>

                                    <div class="controls">
                                        <s:textfield name="user.email" id="email" cssClass="input-medium" required="required"/>
                                    </div>
                                </div>

                                <div class="form-actions">
                                    <s:submit cssClass="btn btn-primary" value="Update my profile"/>
                                </div>

                            </fieldset>
                        </s:form>
                    </div>
                </div>

                <div class="row">
                    <div class="span8">
                        <s:form cssClass="form-horizontal" namespace="/user" action="changePassword.do" method="post">

                            <fieldset>

                                <legend>Update my Password <p class="alert-success">${requestScope.updatePasswordSuccessMessage}</p></legend>

                                <div class="control-group">
                                    <label class="control-label" for="currentpassword">Current password :</label>

                                    <div class="controls">
                                        <s:password id="currentpassword" name="changePasswordForm.currentpassword" cssClass="input-medium" placeholder="min 6 characters" required="required"/>
                                        <p class="help-block alert-error"><c:out value="${requestScope.errorCurrentPassword}"/></p>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="password">New password :</label>

                                    <div class="controls">
                                        <s:password id="password" name="changePasswordForm.password" cssClass="input-medium" placeholder="min 6 characters" required="required"/>
                                        <p class="help-block alert-error"><c:out value="${requestScope.errorPassword}"/></p>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="confirmpassword">Confirm Password :</label>

                                    <div class="controls">
                                        <s:password id="confirmpassword" name="changePasswordForm.confirmpassword" cssClass="input-medium" placeholder="min 6 characters" required="required"/>
                                        <p class="help-block alert-error"><c:out value="${requestScope.errorConfirmationPassword}"/></p>
                                    </div>
                                </div>

                                <div class="form-actions">
                                    <s:submit cssClass="btn btn-primary" value="Update my password"/>
                                </div>
                            </fieldset>
                        </s:form>
                    </div>
                </div>

                <div class="row">
                    <div class="span8">
                        <fieldset>
                            <legend>Delete my account</legend>
                            <div class="alert alert-block alert-error fade in">
                                <p>You are about to remove your account from "Todolist MVC". This will completely
                                    delete all your data and you will be no more able to use your account.
                                    Please be sure.</p>
                                <p>
                                    <a class="btn btn-danger" data-toggle="modal" href="#deleteAccountLink"> <i class="icon-remove icon-white"></i> Delete my account</a>
                                </p>
                                <div class="modal hide" id="deleteAccountLink">
                                    <div class="modal-header">
                                        <h3>Confirmation</h3>
                                    </div>
                                    <div class="modal-body">
                                        <p>Are you sure to delete your account?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <s:form cssClass="form-horizontal" namespace="/user" action="delete.do" method="post">
                                            <p>
                                                <a href="#" class="btn" data-dismiss="modal">No, I'm not sure</a>
                                                <s:submit cssClass="btn btn-danger" value="Yes, I do confirm!"/>
                                            </p>
                                        </s:form>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<%--end content--%>
<%@ include file="../common/footer.jspf" %>

todolist-web-struts/src/main/webapp/WEB-INF/views/user/home.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="s" uri="/struts-tags"%>
<%@ taglib prefix="tl" uri="http://todolist.org/taglib" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="../common/header.jspf"%>

<div class="container">
    <div class="row">
        <div class="span3">
            <%@ include file="../common/sidebar.jspf"%>
        </div>
        <div class="span9">
            <div class="well">
                <div class="page-header">
                    <h1>My Todo list</h1>
                </div>

                <table class="table table-bordered table-striped">

                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>Due Date</th>
                        <th>Priority</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                    </thead>

                    <tbody>
                    <c:forEach items="${requestScope.todoList}" var="currentTodo">
                        <tr>
                            <td>${currentTodo.id}</td>
                            <td>${currentTodo.title}</td>
                            <td><fmt:formatDate value="${currentTodo.dueDate}" pattern="dd/MM/yyyy"/></td>
                            <td><i class="icon-circle-arrow-<tl:priorityIcon priority="${currentTodo.priority}"/>"></i> ${currentTodo.priority}</td>
                            <td><span class="label <tl:statusLabel status="${currentTodo.status}"/> "> ${currentTodo.status}</span></td>
                            <td>
                                <a class="btn btn-mini btn-primary" href="/todo/update?todoId=${currentTodo.id}"><i class="icon-edit icon-white"></i> Edit</a>
                                <a class="btn btn-mini btn-danger" data-toggle="modal" href="#confirm_delete_${currentTodo.id}"><i class="icon-remove icon-white"></i> Delete</a>
                                <div class="modal hide" id="confirm_delete_${currentTodo.id}">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">×</button>
                                        <h3>Confirmation</h3>
                                    </div>
                                    <div class="modal-body">
                                        <p>Are you sure to delete todo ${currentTodo.id} '${currentTodo.title}' ?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <s:form namespace="/todo" action="delete.do" method="post">
                                            <%-- issue with s:hidden : not able to set 'value' attribute with ${currentTodo.id} nor %{currentTodo.id} --%>
                                            <input type="hidden" name="todoId" value="${currentTodo.id}" />
                                            <a href="#" class="btn" data-dismiss="modal">Cancel</a> <s:submit cssClass="btn btn-primary" value="Confirm"/>
                                        </s:form>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </c:forEach>

                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="2"><div align="center">Total = <span class="badge badge-inverse">${requestScope.totalCount}</span></div></td>
                            <td colspan="2"><div align="center">Todo = <span class="badge">${requestScope.todoCount}</span></div></td>
                            <td colspan="2"><div align="center">Done = <span class="badge badge-success">${requestScope.doneCount}</span></div></td>
                        </tr>
                    </tfoot>
                </table>

                <c:if test="${empty requestScope.todoList}">
                    <div class="alert alert-info">
                        <div align="center">Your todo list is empty !</div>
                    </div>
                </c:if>

                <c:if test="${not empty requestScope.todoList}">
                <div align="center">
                    <button class="btn" onclick="javascript:window.print()">
                        <i class="icon-print"></i>
                        Print my todo list
                    </button>
                </div>
                </c:if>

            </div>
        </div>
    </div>
</div>

<%--end content--%>
<%@ include file="../common/footer.jspf"%>

todolist-web-struts/src/main/webapp/WEB-INF/views/user/login.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="s" uri="/struts-tags"%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="../common/header.jspf"%>
<%--content--%>

<div class="container">

    <div class="row">
        <div class="span6 offset3">
            <div class="page-header">
                <h1>Sign in</h1>
            </div>

            <%@ include file="../common/error.jspf"%>

            <s:form cssClass="well form-horizontal" method="post" action="login.do">
                <fieldset>

                    <div class="control-group">
                        <label class="control-label" for="email">Email :</label>
                        <div class="controls">
                            <s:textfield id="email" name="loginForm.email" cssClass="input-medium" placeholder="your@email.com" required="required"/>
                            <p class="help-block alert-error"><c:out value="${requestScope.errorEmail}"/></p>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="password">Password :</label>
                        <div class="controls">
                            <s:password id="password" name="loginForm.password" cssClass="input-medium" placeholder="min 6 characters" required="required"/>
                            <p class="help-block alert-error"><c:out value="${requestScope.errorPassword}"/></p>
                        </div>
                    </div>

                    <div class="form-actions">
                        <s:submit cssClass="btn btn-primary" value="Sign in"/>
                    </div>

                    <div align="center">
                        You don't have an account yet? <a href="/register">Register here for free!</a>
                    </div>

                </fieldset>
            </s:form>

        </div>
    </div>
</div>

<%--end content--%>
<%@ include file="../common/footer.jspf"%>